base_url = "/"
title = "London Education & Art Foundation"
compile_sass = true
build_search_index = false
ignored_content = ["*.kate-swp"]

[markdown]
highlight_code = true
highlight_theme = "inspired-github"

[extra]
meta_description = "Welcome to the London Education & Art Foundation"
logo_path = "logo_leaf.png"
nav_menu = [
     { title = "Home", link = "/"},
     { title = "About Us", link = "/about/"},
     { title = "Blog", link = "/blog/"},
     { title = "Events", link = "/events/"},
     { title = "Gallery", link = "/gallery/"},
     { title = "Membership", link = "/membership/"},
     { title = "Donate", link = "/donate/"},
]
