backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  squash_merges: true

publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

site_url: https://theleaf.london
logo_url: https://theleaf.london/logo_leaf.png

show_preview_links: true
search: true

collections:
  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    delete: false
    format: toml-frontmatter
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "events/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Event Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false }
      - label: "Featured Image"
        name: "extra.thumbnail"
        widget: "image"
        media_library:
          config:
            max_file_size: 512000
      - { label: "Event Type", name: "extra.type", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    delete: false
    format: toml-frontmatter
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "blog/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false }
      - label: "Featured Image"
        name: "extra.thumbnail"
        widget: "image"
        media_library:
          config:
            max_file_size: 512000
      - { label: "Body", name: "body", widget: "markdown" }